name: Deployment
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configure Env Variables
        if: github.ref == 'refs/heads/master'
        run: echo "STAGE=dev" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Python dependencies
        run: pip install pipenv==2020.11.15 && pipenv install
      - name: Install Node dependencies
        run: npm install && npm install -g serverless@3.18.2
      - name: Deploy application
        run: serverless deploy --verbose --stage $STAGE --param "GoogleClientId=${{ secrets.DEV_GOOGLE_CLIENT_ID }}" --param "GoogleClientSecret=${{ secrets.DEV_GOOGLE_CLIENT_SECRET }}"
